stages:
  preprocess:
    cmd: python src/preprocessing.py
    deps:
      - data/cars24data.csv
      - src/preprocessing.py  
    outs:
      - data/processed_train_data.csv
      - data/processed_test_data.csv

  create_features:
    cmd: python src/create_features.py
    deps:
      - data/processed_train_data.csv
      - data/processed_test_data.csv
      - src/create_features.py
    outs:
      - data/features_train_data.csv
      - data/features_test_data.csv
      - data/pipeline.pkl