features:
  chi2percentile: 50
  train_path: data/processed_train_data.csv
  test_path: data/processed_test_data.csv

preprocessing:
  input_data: data/cars24data.csv  
  output_train_data: data/processed_train_data.csv 
  output_test_data: data/processed_test_data.csv  

create_features:
  input_train_data: data/processed_train_data.csv
  input_test_data: data/processed_test_data.csv
  output_train_data: data/features_train_data.csv
  output_test_data: data/features_test_data.csv
  pipeline_output: data/pipeline.pkl